name: Fraud Detection Deployment Pipeline

on:
  push:
    branches: [main]
    paths:
      - '**'
    paths-ignore:
      - 'README.md'
      - '**.ipynb'
      - '**.md'

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.5.0

jobs:
  infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create Lambda Layer
        run: |
          mkdir -p python/lib/python3.9/site-packages
          pip install -r ../requirements.txt -t python/lib/python3.9/site-packages/
          zip -r dependencies.zip python

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init -no-color -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload Initial Model
        working-directory: ..
        run: |
          aws s3 cp models/fraud_detection_pipeline_smote.joblib \
            s3://$(terraform -chdir=infra output -raw model_bucket_name)/model.joblib
          aws s3 cp models/feature_names.json \
            s3://$(terraform -chdir=infra output -raw model_bucket_name)/features.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  model-training:
    name: Train & Update Model
    runs-on: ubuntu-latest
    needs: infrastructure
    if: |
      contains(github.event.commits[0].modified, 'models/') ||
      contains(github.event.commits[0].modified, 'data/')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Train Model
        run: python models/train_fraud_detection_model.py

      - name: Upload New Model
        run: |
          aws s3 cp models/fraud_detection_pipeline_smote.joblib \
            s3://$(terraform -chdir=infra output -raw model_bucket_name)/model.joblib
          aws s3 cp models/feature_names.json \
            s3://$(terraform -chdir=infra output -raw model_bucket_name)/features.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Notify Lambda Update
        run: |
          aws lambda update-function-code \
            --function-name "$(terraform -chdir=infra output -raw lambda_function_arn)" \
            --s3-bucket "$(terraform -chdir=infra output -raw model_bucket_name)" \
            --s3-key model.joblib
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
